/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author L E N O V O
 */
    import javax.swing.*;
    import java.awt.*;
    import java.awt.event.ActionEvent;
    import java.awt.event.ActionListener;
    import java.io.BufferedReader;
    import java.io.FileReader;
    import java.io.IOException;

public class KnightMovesFrame extends javax.swing.JFrame {

    GerakanKuda gerakan = new GerakanKuda();
    private JTextField inputFilePath;
    private JTextArea outputArea;
    
    // Konstruktor
    public KnightMovesFrame() {
        initComponents();
        inputFilePath.setText("///////////////////////////////////////////// isi lokasi data disini (misal: ""C:/Users/sxpix/Documents/data/papan_data.csv"");
    }

    private void HitungKuda(boolean useBFS) {
        String filePath = inputFilePath.getText().trim();
        try (BufferedReader read = new BufferedReader(new FileReader(filePath))) {
            String line;
            outputArea.setText("");
            long start = System.nanoTime();
            while ((line = read.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length != 6) {
                    outputArea.setText("Format tidak valid.");
                    return;
                }

                int ukuran_papan = Integer.parseInt(data[0].trim());
                int awalX = Integer.parseInt(data[1].trim());
                int awalY = Integer.parseInt(data[2].trim());
                int endX = Integer.parseInt(data[3].trim());
                int endY = Integer.parseInt(data[4].trim());
                int langkah = Integer.parseInt(data[5].trim());

                int hasil;
                if (useBFS == true) {
                    hasil = gerakan.HitungLangkahBFS_Iteratif(ukuran_papan, awalX, awalY, endX, endY, langkah);
                } else {
                    hasil = gerakan.HitungLangkahDFS_Rekursif(ukuran_papan, awalX, awalY, endX, endY, langkah);
                }

                outputArea.append("Papan " + ukuran_papan + "x" + ukuran_papan + ", Dari (" + awalX + ", " + awalY + ") ke (" + endX + ", " + endY + ") dalam " + langkah + " langkah: " + hasil + " cara\n");
            }
            long end = System.nanoTime();
            long waktuEksekusi = (end - start) / 1_000_000; // Convert nanoseconds ke milliseconds
            outputArea.append("\nWaktu eksekusi: " + waktuEksekusi + " ms\n");
        } catch (IOException e) {
            outputArea.setText("Terjadi kesalahan membaca file: " + e.getMessage());
        } catch (NumberFormatException e) {
            outputArea.setText("Format angka tidak valid di file CSV.");
        }
    }
    
    // Main untuk menjalankan aplikasi
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new KnightMovesFrame().setVisible(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BFS = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(15, 15, 15));

        BFS.setText("BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });

        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });

        jLabel1.setText("Kalkulator Gerakan Kuda di Papan Catur");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DFS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BFS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(BFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DFS)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        HitungKuda(true); // bfs
    }//GEN-LAST:event_BFSActionPerformed

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        HitungKuda(false); // dfs
    }//GEN-LAST:event_DFSActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFS;
    private javax.swing.JButton DFS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
